### ISSUE TITLE
Integration of vl53l7cx in ros with arduino zero

### ISSUE THREAD

**Issue by DasSchilli** [stm32duino/VL53L7CX#2]
Hello,

I have one vl53l7cx and have some questions.

1. What is the maximum frequency at a resolution of 8x8?
2. Can I change the laser power?
3. What happens if I increase the integration time, better results of distance measuring? What are the maximum ratings ?
4. Sometimes, the distance_mm of the result struct doesn't change, if the ToF-chip get no new value, how can I check if the value is out of range or if its valid? 

I think you forget to uncomment this line.
https://github.com/stm32duino/VL53L7CX/blob/23366c6c52e0aa90b0b49d7f7fb36d7919e75670/src/vl53l7cx_api.cpp#L839

**Comment by cparata** [comment]
Hello @DasSchilli ,
I'm not very expert about the component. You can find more information in the [Datasheet](https://www.st.com/resource/en/datasheet/vl53l7cx.pdf) and in the [User Manual](https://www.st.com/resource/en/user_manual/um3038-a-guide-to-using-the-vl53l7cx-timeofflight-multizone-ranging-sensor-with-90-fov-stmicroelectronics.pdf) or you can try to ask more information in the [ST Community Forum](https://community.st.com/s/) where some experts of the component can answer to your technical questions. Regarding the target status after a reading, you can check the value of the target_status field in the VL53L7CX_ResultsData structure passed by reference to the vl53l7cx_get_ranging_data API and compare it with the values in Table 4 of the User Manual (chapter 5.5, page 14).
I hope that it can help you.
Best Regards,
Carlo

**Comment by DasSchilli** [comment]
Thank you, that helps a lot.
