### ISSUE TITLE
How to implement an application with more than one VL537CX

### ISSUE THREAD

**Issue by DasSchilli** [stm32duino/VL53L7CX#3]
Hello,

I want to implement an application with more than one VL537CX with an Arduino board. I found the documentation in the UserGuide 2.3 Schematics and I2C configuration, but after I follow the instructions, both sensors aren't starting ranging.

Can you provide an example how to configure a multisensor setup? 

Best regards

**Comment by cparata** [comment]
Hello @DasSchilli ,
you can give a look at [this example](https://github.com/stm32duino/X-NUCLEO-53L7A1/blob/main/examples/X_NUCLEO_53L7A1_MultiSensorRanging/X_NUCLEO_53L7A1_MultiSensorRanging.ino) for the relative expansion board based on VL53L7CX sensor. In this expansion board we can control 3 different VL53L7CX sensors at the same time.
Best Regards,
Carlo

**Comment by DasSchilli** [comment]
Thanks a lot.

**Comment by DasSchilli** [comment]
In this [example](https://github.com/stm32duino/X-NUCLEO-53L7A1/blob/main/examples/X_NUCLEO_53L7A1_MultiSensorRanging/X_NUCLEO_53L7A1_MultiSensorRanging.ino) the data isn't reading out  at the same time or I am wrong?

**Comment by cparata** [comment]
Hello @DasSchilli ,
it depends what you mean "at the same time". In a "bare-metal" system all the instructions are sequential, so you can check sequentially when the data are available for the several sensors. If you don't want to use the polling mode, you could try to use the reading in interrupt mode and wait until the data are available for all sensors, but I don't know if the final behavior changes with respect to the polling mode case.
Best Regards,
Carlo

**Comment by DasSchilli** [comment]
Thanks a lot.
