### ISSUE TITLE
VL53L7CX example code

### ISSUE THREAD

**Issue by TraxerMoon** [stm32duino/VL53L7CX#4]
Hello,

I have a problem about testing your example code "Hello World". I have used the ESP32 DevKit V4 with Arduino Framework. 
Unfortunately,  there is always an error during initialization. 
![image](https://github.com/stm32duino/VL53L7CX/assets/141307770/88a97278-7599-4f08-8e85-f81dfb307665)

Moreover,  I have tried to read the adresse of the sensor (it should be 0x52) but i have got 0x29.
![image](https://github.com/stm32duino/VL53L7CX/assets/141307770/a2efd8bb-6273-43cd-bd0c-c6ba3e6d3e28)

can somebody help me to solve this problem ?

Thanks in advance.

Best regards
Traxer

**Comment by cparata** [comment]
Hello @TraxerMoon ,
thanks for sharing this issue. Could you try to patch line number 87 of platform.cpp file of the library in this way:

`p_platform->dev_i2c->endTransmission(true);`

In past, we had a similar problem for ESP32 platforms on VL53L4CX library and we applied [this patch](https://github.com/stm32duino/VL53L4CX/commit/8adf1ba2ff45d9ee5ded3e0b457c431a8bb9d0cf).

Regarding the I2C address, I guess that the printed one is in 7-bit format (0x29). Normally, in ST datasheets the I2C addresses are represented in 8-bit format, so you get 0x52.

Let me know if the patch works on your side, so I can release a new version of the library including the patch for ESP32.

Best Regards,
Carlo

**Comment by TraxerMoon** [comment]
Hi Carlo,

thanks for your reply. 

After applying that patch, it works.  Thanks again :)

Best regards
Traxer

**Comment by cparata** [comment]
Hi @TraxerMoon ,
great! I released a new version of the library (1.0.2) that includes the fix.
Best Regards,
Carlo
